agent {
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"

    server_address = "spire-server"
    server_port = "8081"

    trust_domain = "runtime-shield"

    insecure_bootstrap = true
}

plugins {

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data"
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {}
    }

    WorkloadAttestor "docker" {
        plugin_data {}
    }

}