services:
  keycloak:
    container_name: keycloak_mcp
    image: quay.io/keycloak/keycloak:26.5.3
    command: ["start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - C:/Users/Lenovo/Desktop/keycloakify-starter/dist_keycloak/keycloak-theme-for-kc-26.2-and-above.jar:/opt/keycloak/providers/keycloakify.jar