server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "runtime-shield"
    data_dir = "/run/spire/data"
    log_level = "DEBUG"
}

plugins {

    DataStore "sql" {
        plugin_data {
            database_type = "postgres"
            connection_string = "dbname=spire user=postgres password=postgres host=spire-db port=5432 sslmode=disable"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/run/spire/data/keys.json"
        }
    }

}